[project]
name = "mlxweek5"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
python = "3.10"
requires-python = "==3.10.*"
dependencies = [
    "openai-whisper>=20240930",
    "ruff>=0.9.7",
    "torch>=2.6.0",
]
